### ISSUE TITLE
YAMLParseError

### ISSUE THREAD

**Issue by vbtueli** [HCLonely/AWA-Helper#1]
下载编译还需要安装 Node.js 吗?
出现下面错误 
 
```
C:\snapshot\AWA-Helper\node_modules\yaml\dist\compose\composer.js:70
                this.errors.push(new errors.YAMLParseError(pos, code, message));
                                 ^
YAMLParseError: Unexpected scalar at node end at line 2, column 340:

…1-1e38-aaef7e6dd0a2; s_channelstack=[['Referrers','1617106444986'],['Referrers…
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    at C:\snapshot\AWA-Helper\node_modules\yaml\dist\compose\composer.js:70:34
    at Object.resolveEnd (C:\snapshot\AWA-Helper\node_modules\yaml\dist\compose\resolve-end.js:31:21)
    at Object.resolveFlowScalar (C:\snapshot\AWA-Helper\node_modules\yaml\dist\compose\resolve-flow-scalar.js:35:27)
    at Object.composeScalar (C:\snapshot\AWA-Helper\node_modules\yaml\dist\compose\compose-scalar.js:11:29)
    at composeNode (C:\snapshot\AWA-Helper\node_modules\yaml\dist\compose\compose-node.js:24:34)
    at Object.resolveBlockMap (C:\snapshot\AWA-Helper\node_modules\yaml\dist\compose\resolve-block-map.js:80:19)
    at Object.composeCollection (C:\snapshot\AWA-Helper\node_modules\yaml\dist\compose\compose-collection.js:13:36)
    at Object.composeNode (C:\snapshot\AWA-Helper\node_modules\yaml\dist\compose\compose-node.js:31:38)
    at Object.composeDoc (C:\snapshot\AWA-Helper\node_modules\yaml\dist\compose\compose-doc.js:32:23)
    at Composer.next (C:\snapshot\AWA-Helper\node_modules\yaml\dist\compose\composer.js:150:40) {
  code: 'UNEXPECTED_TOKEN',
  pos: [ 360, 2470 ],
  linePos: [ { line: 2, col: 340 }, { line: 2, col: 2450 } ]
}
```

**Comment by HCLonely** [comment]
你这应该是配置格式有误

vbtueli ***@***.***> 于2022年4月22日周五 13:31写道：

**Comment by vbtueli** [comment]
ok，我再试一次看看，感谢

**Comment by vbtueli** [comment]
回报一下进度…

在 awaCookie 里面全贴仍会报错，把 REMEMBERME 之前全删，只保留 REMEMBERME, PHPSESSID, sc 和 home_site 就可以正常运行

**Comment by HCLonely** [comment]
实际上只会用到`REMEMBERME`,cookie里有`'`会解析失败
