### ISSUE TITLE
docker版无法登录

### ISSUE THREAD

**Issue by MurasameCyan** [HCLonely/AWA-Helper#23]
一周前是正常使用的突然就这样了
`
> awa-helper@2.3.0 start
> cd dist && node index.js
  ______   __       __   ______           __    __            __                               
 /      \ /  |  _  /  | /      \         /  |  /  |          /  |                              
/$$$$$$  |$$ | / \ $$ |/$$$$$$  |        $$ |  $$ |  ______  $$ |  ______    ______    ______  
$$ |__$$ |$$ |/$  \$$ |$$ |__$$ | ______ $$ |__$$ | /      \ $$ | /      \  /      \  /      \ 
$$    $$ |$$ /$$$  $$ |$$    $$ |/      |$$    $$ |/$$$$$$  |$$ |/$$$$$$  |/$$$$$$  |/$$$$$$  |
$$$$$$$$ |$$ $$/$$ $$ |$$$$$$$$ |$$$$$$/ $$$$$$$$ |$$    $$ |$$ |$$ |  $$ |$$    $$ |$$ |  $$/ 
$$ |  $$ |$$$$/  $$$$ |$$ |  $$ |        $$ |  $$ |$$$$$$$$/ $$ |$$ |__$$ |$$$$$$$$/ $$ |      
$$ |  $$ |$$$/    $$$ |$$ |  $$ |        $$ |  $$ |$$       |$$ |$$    $$/ $$       |$$ |      
$$/   $$/ $$/      $$/ $$/   $$/         $$/   $$/  $$$$$$$/ $$/ $$$$$$$/   $$$$$$$/ $$/       
                                                                 $$ |                          
                                                                 $$ |                   V2.3.0 
                                                                 $$/               by HCLonely 
版本更新内容：
┌─────────┬──────────────────────────────────┐
│ (index) │              Values              │
├─────────┼──────────────────────────────────┤
│    0    │ '优化：Steam挂机任务识别附加Arp' │
│    1    │  '优化：Steam社区活动时间判断'   │
│    2    │      '更新：每日任务数据库'      │
└─────────┴──────────────────────────────────┘
[2023-06-10 11:51:04] 正在检测更新...[2023-06-10 11:51:04] webUI服务器已启动，请打开 https://localhost:3456 查看
当前为最新版！
[2023-06-10 11:51:05] 正在更新 AWA Cookie...Error: awaCookie 已过期, 请重新获取！
[2023-06-10 11:51:05] 正在更新 awaCookie |---->
[2023-06-10 11:51:07] 正在打开https://www.alienwarearena.com/...OK
[2023-06-10 11:51:17] 正在打开登录表单...OK
[2023-06-10 11:51:21] 正在输入用户名...OK
[2023-06-10 11:51:24] 正在输入密码...OK
[2023-06-10 11:51:28] 正在勾选 Remember Me 复选框...OK
[2023-06-10 11:51:32] 正在点击登录按钮...OK
[2023-06-10 11:51:32] 正在验证是否成功登录...[2023-06-10 11:54:32] 更新 awaCookie 失败 <-----|
page.waitForNavigation: Timeout 180000ms exceeded.
=========================== logs ===========================
waiting for navigation until "load"
============================================================
    at DailyQuest.login (/usr/src/app/dist/DailyQuest.js:210:24)
    at async DailyQuest.init (/usr/src/app/dist/DailyQuest.js:121:18)
    at async /usr/src/app/dist/index.js:215:24 {
  name: 'TimeoutError'
}
[2023-06-10 11:54:32] 正在推送...推送成功
npm notice 
npm notice New minor version of npm available! 9.5.1 -> 9.7.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.7.1>
npm notice Run `npm install -g npm@9.7.1` to update!
npm notice 
`

**Comment by HCLonely** [comment]
经测试可以正常登录，请检查你的网络
![image](https://github.com/HCLonely/AWA-Helper/assets/26346802/cf143c4d-d491-41e2-a2ec-a0883ab1e66b)

**Comment by MurasameCyan** [comment]
$$/               by HCLonely 
[2023-06-13 07:20:53] 正在检测更新...[2023-06-13 07:20:53] webUI服务器已启动，请打开 https://localhost:3456 查看
当前为最新版！
[2023-06-13 07:20:54] 正在更新 AWA Cookie...OK
[2023-06-13 07:20:55] 正在验证 AWA Token...OK
[2023-06-13 07:21:05] 已连续登录 1 / 7 天，获得 1 ARP
[2023-06-13 07:21:05] 本月已登录 8 天，获得 3 ARP
[2023-06-13 07:21:05] 正在获取用户 Personalization 信息...OK
[2023-06-13 07:21:08] 正在获取任务信息...OK
[2023-06-13 07:21:09] 当前任务信息：
┌──────────────────────────┬──────────┬───────────┬───────────────┐
│         (index)          │   状态   │ 已获得ARP │ 最大可获得ARP │
├──────────────────────────┼──────────┼───────────┼───────────────┤
│ 每日任务[Juices Flowing] │ '未完成' │     0     │       0       │
│       AWA在线任务        │ '未完成' │     0     │       5       │
│      Twitch在线任务      │ '未完成' │     0     │      15       │
│        Steam任务         │   '-'    │     0     │      '-'      │
└──────────────────────────┴──────────┴───────────┴───────────────┘


使用cookie是可以正常用的 应该不是网络问题 ..

**Comment by HCLonely** [comment]
已取消自动登录功能
