### ISSUE TITLE
北美账号登录失败

### ISSUE THREAD

**Issue by Z-Y00** [HCLonely/AWA-Helper#26]
试了两种 url ， 发现都不成功。 谢谢帮助
```
[2023-07-09 06:07:37] 正在打开https://na.alienwarearena.com/...[2023-07-09 06:07:41] 更新 awaCookie 失败 <-----|
page.goto: Navigation failed because page crashed!
=========================== logs ===========================
navigating to "https://na.alienwarearena.com/", waiting until "load"
============================================================
    at DailyQuest.login (/home/yoo/AWA-Helper/dist/DailyQuest.js:190:24)
    at async DailyQuest.init (/home/yoo/AWA-Helper/dist/DailyQuest.js:124:18)
    at async /home/yoo/AWA-Helper/dist/index.js:231:24 {
  name: 'Error'
}
```

```
[2023-07-09 05:57:57] 正在打开https://www.alienwarearena.com/...[2023-07-09 05:58:01] 更新 awaCookie 失败 <-----|
page.goto: Navigation failed because page crashed!
=========================== logs ===========================
navigating to "https://www.alienwarearena.com/", waiting until "load"
============================================================
    at DailyQuest.login (/home/yoo/AWA-Helper/dist/DailyQuest.js:190:24)
    at async DailyQuest.init (/home/yoo/AWA-Helper/dist/DailyQuest.js:124:18)
    at async /home/yoo/AWA-Helper/dist/index.js:231:24 {
  name: 'Error'
}
```

**Comment by HCLonely** [comment]
应该是电脑配置不够导致浏览器崩溃

**Comment by Z-Y00** [comment]
从内存上来看，距离 out of memory 还挺远的唉.
我是在 Windows 下的 WSL 里跑的
![image](https://github.com/HCLonely/AWA-Helper/assets/23717414/6685bd33-b0bf-45e7-9706-913002c36767)

**Comment by HCLonely** [comment]
你试一下不用WSL

**Comment by hsiayuchih** [comment]
我也遇到这个问题了，用的是cmd跑的

**Comment by hsiayuchih** [comment]
> ~~我也遇到这个问题了，用的是cmd跑的~~
解决了

**Comment by HCLonely** [comment]
已取消自动登录功能
