### ISSUE TITLE
awa-helper 登录twitch失败

### ISSUE THREAD

**Issue by Darkware-2019** [HCLonely/AWA-Helper#28]
您好，最近在使用 awa-helper登录twitch出现报错：
大致的后台日志是下面这个样子的：尝试过退出twitch并重新获取cookie发现不能解决问题，重新部署awa-helper也不能解决问题
服务器是在美国西部的AzureVPS，Linux2204LTS，环境都是使用npm install一键安装的，NodeJS版本是20.x
Twitch扩展已经授权

[2023-10-19 05:31:53] 正在检测更新...[2023-10-19 05:31:53] webUI服务器已启动，请打开 http://localhost:3456 查看
当前为最新版！
[2023-10-19 05:31:53] 正在更新 AWA Cookie...OK
[2023-10-19 05:31:53] 正在验证 AWA Token...OK
[2023-10-19 05:31:58] 已连续登录 2 / 7 天，获得 1 + 0 ARP
[2023-10-19 05:31:58] 本月已登录 9 天，获得 Spooky Kitty
[2023-10-19 05:31:58] 正在获取任务信息...OK
[2023-10-19 05:31:59] 当前任务信息：
┌─────────────────────────────────┬──────────┬───────────┬─────────────┬───────────────┐
│             (index)             │   状态   │ 已获得ARP │ 额外获得ARP │ 最大可获得ARP │
├─────────────────────────────────┼──────────┼───────────┼─────────────┼───────────────┤
│   每日任务[New Hive Members!]   │ '已完成' │    '5'    │     '0'     │       5       │
│           AWA在线任务           │ '未完成' │    '4'    │     '0'     │      '5'      │
│         Twitch在线任务          │ '未完成' │    '0'    │  undefined  │      15       │
│            Steam任务            │   '-'    │    '0'    │  undefined  │      '-'      │
│ 每日任务US[Day 4: Space Memory] │ '未完成' │    '0'    │     '0'     │      '-'      │
└─────────────────────────────────┴──────────┴───────────┴─────────────┴───────────────┘
[2023-10-19 05:31:59] 正在发送 AWA 在线心跳...OK
[2023-10-19 05:32:09] 正在获取Twitch任务每日最大 ARP...Error(0)
TypeError: Cannot read properties of null (reading 'perkTextShort')
    at /home/azureuser/awa/dist/DailyQuest.js:1719:69
    at Array.forEach (<anonymous>)
    at /home/azureuser/awa/dist/DailyQuest.js:1718:52
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/azureuser/awa/dist/index.js:271:9
[2023-10-19 05:32:11] 正在初始化 TwitchTrack...OK
[2023-10-19 05:32:11] 正在检测是否授权 Twitch 扩展...Error
[2023-10-19 05:32:11] 正在重试第 1 次...Error
[2023-10-19 05:32:12] 正在重试第 2 次...Error
[2023-10-19 05:32:13] 正在重试第 3 次...Error(0)
TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "X-Device-Id"
    at ClientRequest.setHeader (node:_http_outgoing:655:3)
    at new ClientRequest (node:_http_client:286:14)
    at Object.request (node:https:377:10)
    at RedirectableRequest._performRequest (/home/azureuser/awa/node_modules/follow-redirects/index.js:284:24)
    at new RedirectableRequest (/home/azureuser/awa/node_modules/follow-redirects/index.js:66:8)
    at Object.request (/home/azureuser/awa/node_modules/follow-redirects/index.js:523:14)
    at dispatchHttpRequest (/home/azureuser/awa/node_modules/axios/lib/adapters/http.js:262:25)
    at new Promise (<anonymous>)
    at httpAdapter (/home/azureuser/awa/node_modules/axios/lib/adapters/http.js:49:10)
    at request (/home/azureuser/awa/dist/tool.js:197:30) {
  code: 'ERR_HTTP_INVALID_HEADER_VALUE'
}
[2023-10-19 05:32:14] 正在初始化 ASF...OK

**Comment by HCLonely** [comment]
twitch cookie缺少`unique_id`
`twitchCookie: 'unique_id=*****; auth-token=*****'`
